import { createElement } from "@lwc/engine-dom";
import UswdsFooterContainer from "c/uswdsFooterContainer";

describe("c-uswds-footer-container", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-uswds-footer-container", {
      is: UswdsFooterContainer
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });

  it("should render the component in Big mode", async () => {
    const element = createElement("c-uswds-footer-container", {
      is: UswdsFooterContainer
    });
    element.type = "Big";
    document.body.appendChild(element);

    return Promise.resolve().then(() => {
      const footer = element.shadowRoot.querySelector("footer");
      expect(footer.classList.contains("usa-footer--big")).toBe(true);
    });
    await expect(element).toBeAccessible();
  });

  it("should render the component in Medium mode", async () => {
    const element = createElement("c-uswds-footer-container", {
      is: UswdsFooterContainer
    });
    element.type = "Medium";
    document.body.appendChild(element);

    return Promise.resolve().then(() => {
      const footer = element.shadowRoot.querySelector("footer");
      expect(footer.classList.contains("usa-footer")).toBe(true);
      expect(footer.classList.contains("usa-footer--big")).toBe(false);
      expect(footer.classList.contains("usa-footer--slim")).toBe(false);
    });

    await expect(element).toBeAccessible();
  });

  it("should render the component in Slim mode", async () => {
    const element = createElement("c-uswds-footer-container", {
      is: UswdsFooterContainer
    });
    element.type = "Slim";
    document.body.appendChild(element);

    return Promise.resolve().then(() => {
      const footer = element.shadowRoot.querySelector("footer");
      expect(footer.classList.contains("usa-footer--slim")).toBe(true);
    });
    await expect(element).toBeAccessible();
  });
});
