import { createElement } from "@lwc/engine-dom";
import UswdsIcon from "c/uswdsIcon";

describe("c-uswds-icon", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-uswds-icon", {
      is: UswdsIcon
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });

  it('should render sprite icon when iconName starts with "usa_"', () => {
    const element = createElement("c-uswds-icon", {
      is: UswdsIcon
    });
    element.iconName = "usa_account_balance";
    document.body.appendChild(element);

    const svgElement = element.shadowRoot.querySelector("svg");
    const useElement = element.shadowRoot.querySelector("use");
    const imgElement = element.shadowRoot.querySelector("img");

    expect(svgElement).not.toBeNull();
    expect(useElement).not.toBeNull();
    expect(imgElement).toBeNull();
  });

  it('should render standalone icon when iconName does not start with "usa_"', () => {
    const element = createElement("c-uswds-icon", {
      is: UswdsIcon
    });
    element.iconName = "file";
    document.body.appendChild(element);

    const imgElement = element.shadowRoot.querySelector("img");
    const svgElement = element.shadowRoot.querySelector("svg");

    expect(imgElement).not.toBeNull();
    expect(svgElement).toBeNull();
  });

  it("should not render any icon when iconName is not provided", () => {
    const element = createElement("c-uswds-icon", {
      is: UswdsIcon
    });
    document.body.appendChild(element);

    const imgElement = element.shadowRoot.querySelector("img");
    const svgElement = element.shadowRoot.querySelector("svg");

    expect(imgElement).toBeNull();
    expect(svgElement).toBeNull();
  });
});
